name: vocdoni
description: Decentralized anonymous E2E verifiable voting system client app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.8.9+33

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # dvote: ^0.18.0  # Ok on Android (native crypto)
  dvote: ^0.18.2  # Needed for iOS (dart crypto)
  dvote_common:
    git:
      url: https://gitlab.com/vocdoni/dvote-flutter-common.git
      ref: 565d438
  eventual: ^0.10.2
  protobuf: ^1.0.1
  uni_links: ^0.4.0
  url_launcher: ^5.7.5
  http: ^0.12.2
  flutter_html: ^0.11.1
  qr_flutter: ^3.2.0
  firebase_messaging: ^7.0.0
  r_scan: ^0.1.4+1  # Fails on Android
  # r_scan:         # Fails on iOS
  #   git:
  #     url: git://github.com/masewo/r_scan.git
  #     ref: f91ebf9032c63d235782b663752afb7947359c22
  permission_handler: ^5.0.1+1
  feather_icons_flutter: ^4.7.4
  path_provider: ^1.6.21
  pull_to_refresh: ^1.6.2
  mixpanel_analytics: ^1.2.1
  cupertino_icons: ^1.0.0
  rainbow_color: ^0.1.1
  percent_indicator: "^2.1.7+2"
  mdi: ^3.0.0


  # WORKAROUND
  # TODO: Investigate why Flutter does not find the dependencies below
  # from dvote_flutter_common unless the dependency itself is on pub.dev
  flutter_spinkit: ^4.1.2+1
  cached_network_image: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
      - family: Open Sans
        fonts:
          - asset: assets/fonts/OpenSans-Light.ttf
            weight: 300
          - asset: assets/fonts/OpenSans-Regular.ttf
            weight: 400
          - asset: assets/fonts/OpenSans-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/OpenSans-Bold.ttf
            weight: 700

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/
    - assets/icon/icon-sm.png
    #- assets/media/calendar.png
    #- assets/media/home.png
    #- assets/media/house.png
    #- assets/media/mountain.png
    #- assets/media/plane.png
    #- assets/media/world.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon-round.png"
  
